### ISSUE TITLE
Adicionar licença do projeto

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#10]
**Descreva a solução que você gostaria**

Projeto necessita de uma licença que seja de acordo com o projeto apresentado.

**Descreva uma alternativa considerada**

Acordar com os membros da equipe e adicionar a licença definida no projeto.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by cantuariavc** [comment]
A licença foi adicionada na master e não foi comitada na develop.

**Comment by cantuariavc** [comment]
Houve uma confusão porque a develop e merjada na master e descontinuada, mas continuava como branch principal.
