### ISSUE TITLE
Colocar imagens do Projeto na Wiki

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#135]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

A wiki não possui imagens ou GIFs do projeto em si rodando

**Descreva a solução que você gostaria**

Devem ser adicionadas imagens ou GIFs do projeto na Wiki, na Homepage;

**Descreva uma alternativa considerada**

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
Está issue já existia no repositório, disponível em: https://github.com/fga-eps-mds/2019.2-Amika-Wiki/issues/133
