### ISSUE TITLE
[DOC01] Criar documento de visão

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#20]
**Descreva a solução que você gostaria**
Criar documento com a definição do escopo do projeto e o seu propósito. Uma instrução clara do problema, solução proposta e os recursos de alto nível do produto que ajudam a estabelecer expectativas e a reduzir riscos.

**Descreva uma alternativa considerada**
Criação do documento de visão.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by MaiconMares** [comment]
**2. Posicionamento**


**2.1 Oportunidade de Negócios**
Atualmente a matéria Felicidade ofertada no Campus da Universidade de Brasília localizado no Gama, Faculdade do Gama, sofre o problema de organização de notas, trabalhos e eventos. Para solucionar esse problema o professor da disciplina utiliza anotações que tornam o trabalho exaustivo e lento e acabam por não resolver o problema de organização, visto que atrasos quanto ao lançamento de notas, organização de datas e coisas do gênero ainda ocorrem todo semestre. De acordo com essa realidade, o aplicativo (adicionar nome) tem por objetivo tornar mais simples e rápido o processo de organização de datas, comunicação de notas e avisos aos alunos e interação entre esses e o professor.


**2.2 Descrição do problema**

| O problema de         | realizar o gerenciamento de notas, grupos da disciplina, coleta de dados da disciplina e monitorar as atividades pessoais dos alunos manualmente                                                                                          |
|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| afeta                 | alunos e professor                                                                                                                                                                                                                        |
| cujo impacto é        | um processo de definição e organização de datas e eventos lento e cansativo, além de muitas vezes falhar e ser novamente modificado                                                                                                       |
| uma boa solução seria | um sistema capaz de tornar automático o lançamento de notas e avisos, coleta de dados a respeito da disciplina, organização de grupos da mesma e monitorar atividades pessoais dos alunos por um canal não poluído com outras informações |

**2.3 Sentença de posição do produto**

| Para            | O professor e discentes da disciplina de Felicidade                                                                        |
|-----------------|----------------------------------------------------------------------------------------------------------------------------|
| Que             | necessitam de automatizar e tornar simples suas tarefas relacionadas à disciplina                                          |
| O               | (colocar nome do aplicativo quando for definido)                                                                           |
| Que             | gerencia atividades e permite a interação direta entre aluno e professor                                                   |
| Diferente da    | plataforma Moodle                                                                                                          |
| O nosso produto | Não polui a interface do usuário com informações desnecessárias de outras matérias e possui velocidade de tráfego superior |

**Comment by MaiconMares** [comment]
> **2. Posicionamento**
> 
> **2.1 Oportunidade de Negócios**
> Atualmente a matéria Felicidade ofertada no Campus da Universidade de Brasília localizado no Gama, Faculdade do Gama, sofre o problema de organização de notas, trabalhos e eventos. Para solucionar esse problema o professor da disciplina utiliza anotações que tornam o trabalho exaustivo e lento e acabam por não resolver o problema de organização, visto que atrasos quanto ao lançamento de notas, organização de datas e coisas do gênero ainda ocorrem todo semestre. De acordo com essa realidade, o aplicativo (adicionar nome) tem por objetivo tornar mais simples e rápido o processo de organização de datas, comunicação de notas e avisos aos alunos e interação entre esses e o professor.
> 
> **2.2 Descrição do problema**
> 
> O problema de	realizar o gerenciamento de notas, grupos da disciplina, coleta de dados da disciplina e monitorar as atividades pessoais dos alunos manualmente
> afeta	alunos e professor
> cujo impacto é	um processo de definição e organização de datas e eventos lento e cansativo, além de muitas vezes falhar e ser novamente modificado
> uma boa solução seria	um sistema capaz de tornar automático o lançamento de notas e avisos, coleta de dados a respeito da disciplina, organização de grupos da mesma e monitorar atividades pessoais dos alunos por um canal não poluído com outras informações
> **2.3 Sentença de posição do produto**
> 
> Para	O professor e discentes da disciplina de Felicidade
> Que	necessitam de automatizar e tornar simples suas tarefas relacionadas à disciplina
> O	(colocar nome do aplicativo quando for definido)
> Que	gerencia atividades e permite a interação direta entre aluno e professor
> Diferente da	plataforma Moodle
> O nosso produto	Não polui a interface do usuário com informações desnecessárias de outras matérias e possui velocidade de tráfego superior
Só queria que vocês avaliassem o que falta em meu documento e como posso fazer para alinhar o título das colunas e aumentar a fonte dos títulos principais.

**Comment by MaiconMares** [comment]
<h2>2. Posicionamento</h2>

<h3>2.1 Oportunidade de Negócios</h3>
Atualmente a matéria Felicidade ofertada no Campus da Universidade de Brasília localizado no Gama, Faculdade do Gama, sofre o problema de organização de notas, trabalhos e eventos. Para solucionar esse problema o professor da disciplina utiliza anotações que tornam o trabalho exaustivo e lento e acabam por não resolver o problema de organização, visto que atrasos quanto ao lançamento de notas, organização de datas e coisas do gênero ainda ocorrem todo semestre. De acordo com essa realidade, o aplicativo (adicionar nome) tem por objetivo tornar mais simples e rápido o processo de organização de datas, comunicação de notas e avisos aos alunos e interação entre esses e o professor.


<h3>2.2 Descrição do problema</h3>
<table>
<tr><td style="text-align: center;"> O problema de         </td><td style="text-align: center;"> realizar o gerenciamento de notas, grupos da disciplina, coleta de dados da disciplina e monitorar as atividades pessoais dos alunos manualmente                                                                                          </td></tr>
<tr><td style="text-align: center;"> afeta                 </td><td style="text-align: center;"><center> alunos e professor                                                                                                                                                                                                                        </td></tr>
<tr><td style="text-align: center;">cujo impacto é        </td><td style="text-align: center;"> um processo de definição e organização de datas e eventos lento e cansativo, além de muitas vezes falhar e ser novamente modificado</td></tr>
<tr><td style="text-align: center;"> uma boa solução seria </td><td style="text-align: center;"> um sistema capaz de tornar automático o lançamento de notas e avisos, coleta de dados a respeito da disciplina, organização de grupos da mesma e monitorar atividades pessoais dos alunos por um canal não poluído com outras informações </td></tr>
</table>
<h3>2.3 Sentença de posição do produto</h3>
<table>
<tr><td style="text-align: center;"> Para            </td><td style="text-align: center;"> O professor e discentes da disciplina de Felicidade                                                                        </td></tr>
<tr><td style="text-align: center;"> Que             </td><td style="text-align: center;"> necessitam de automatizar e tornar simples suas tarefas relacionadas à disciplina                                          </td></tr>
<tr><td style="text-align: center;"> O               </td><td style="text-align: center;"> (colocar nome do aplicativo quando for definido)                                                                           </td></tr>
<tr><td style="text-align: center;"> Que             </td><td style="text-align: center;"> gerencia atividades e permite a interação direta entre aluno e professor</td>                                                   </tr>
<tr><td style="text-align: center;"> Diferente da</td>    <td style="text-align: center;"> plataforma Moodle</td></tr>                                                                                          
<tr><td style="text-align: center;"> O nosso produto </td><td style="text-align: center;"> Não polui a interface do usuário com informações desnecessárias de outras matérias e possui velocidade de tráfego superior </td></tr>
</table>

**Comment by danilow200** [comment]
**6. Restrições**

- O aplicativo deve estar utilizável para o usuário até o final de novembro de 2019.
- Deve-se desenvolver o aplicativo ao decorrer da matéria de Métodos de Desenvolvimento de Software e de Engenharia de Produto de Software, da Universidade de Brasília, é o mesmo deve ser desenvolvido pelo o grupo de estudantes designados.
- No processo de construção do aplicativo deve-se optar por ferramentas de baixo custo ou de ferramentas livres, que minimizem o custo final do projeto.
- O aplicativo deve permitir o acesso a internet.
- Deve possuir um meio de interação entre os alunos, monitores e professor.
- O aplicativo tem que ser uma plataforma cujo o aluno possa se sentir mais feliz ao utilizá-la.
- Deve ser implementado um sistema de guildas no aplicativo.
- Deve rodar em sistemas operacionais de smartphones(Android, IOS).

**Comment by GustavoAPS** [comment]
**Visão Geral do Produto**

**Perspectiva do produto**

O sistema terá a função de auxiliar a disciplina de felicidade por meio de recursos que permitam acompanhamento dos alunos e a interação entre os mesmos, tais recursos serão implementados junto a estratégias de gamificação, de forma que seu uso seja mais atraente e natural, outra necessidade é de que o professor e a equipe de monitores tenham acesso a atividades e as interações dos usuários.

Recurso | Detalhes
-- | --
Agenda pessoal | Nessa agenda o aluno pode listar suas atividades, a agenda pode ser publicada ou ser privada ao aluno
Enquetes | Feitas em tempo real pelo professor da disciplina para apontar questões levantadas na aula
Controle de cadastro | Alunos matriculados podem ter cadastro na aplicação e o controle de cadastros deve estar disponível para o professor e monitores
Marcador para o nível de felicidade dos alunos | O feedback do nível de felicidade dos alunos deve ser mostrado em forma de uma barra de progresso
Grupos | Deve ser possível formar grupos entre os alunos, tal recurso vai ser gamificado em forma de guildas previamente definidas
Customização pessoal | Customização da aplicação conforme aspectos definidos na gamificação, como stickers, badges, troféus e outros recursos cosméticos.
Barra de progresso na disciplina | Uma barra de progresso que acompanha a progressão do aluno na disciplina
Tarefas | Tarefas que podem ser acessadas pelo alunos
Mural | Quadro de avisos para os alunos, colocados pelos próprios alunos ou pelo professor e monitores para avisar sobre tarefas e lembretes

**Comment by MateusO97** [comment]
Resolvido em #36
