### ISSUE TITLE
[DOC02] Criar termo de abertura do projeto (TAP)

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#21]
**Descreva a solução que você gostaria**
Criar documento que descreva o motivo da existência do projeto.

**Descreva uma alternativa considerada**
Criação do termo de abertura do projeto(TAP)

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by MateusO97** [comment]
Resolvido em #31
