### ISSUE TITLE
Fazer uma reunião com o cliente

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#24]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Definir o escopo do projeto.

**Descreva a solução que você gostaria**
Fazer uma reunião com o cliente.

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by cantuariavc** [comment]
Áudio zipado da reunião realizada com o cliente professor Wander:
[Felicidade - Reunião 01 - 05-09.zip](https://github.com/fga-eps-mds/2019.2-Amika-Wiki/files/3588050/Felicidade.-.Reuniao.01.-.05-09.zip)
