### ISSUE TITLE
[DOC06] Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#25]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Gostaria que fosse criado um protótipo para apresentar ao cliente e para ser usado na criação do front-end. 

**Descreva a solução que você gostaria**
Criar um protótipo de alta fidelidade com o uso de ferramentas.

**Informações adicionais**
A criação do protótipo depende da issue #24 

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by MaiconMares** [comment]
Segue o primeiro protótipo que eu fiz. Porém, é apenas a primeira versão sem os requisitos reais do cliente. Link: https://marvelapp.com/cd4d84e

**Comment by Matheus456** [comment]
Gostei @MaiconMares, ficou bacana! Só vamos precisar de algumas mudanças, pois definimos alguns requisitos hoje com o nosso cliente(Professor Wander) e até amanhã eles já devem estar documentados.

**Comment by Matheus456** [comment]
@ithaloazevedo  @thefael Coloquem o link dos protótipos de vocês aqui também para que a gente possa decidir qual iremos usar. 
Precisamos validar com o cliente e documentar ele.

**Comment by ithaloazevedo** [comment]
https://ithaloazvd.wixsite.com/meusite
