### ISSUE TITLE
Criar logotipo

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#26]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Gostaria que fosse criado um logotipo para a representação gráfica do projeto.

**Descreva a solução que você gostaria**
Criar um logotipo com o uso de ferramentas.

**Informações adicionais**
A criação da logo depende da issue #24

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by GustavoAPS** [comment]
Por meio de votação no grupo de desenvolvimento, um dos designs de logotipo foi escolhido
Segue abaixo o logo aprovado: 

![logo sailor moon](https://user-images.githubusercontent.com/32441692/64468793-21928880-d0ff-11e9-9128-7f98ed726608.png)

@Matheus456 
@MateusO97
@cantuariavc

**Comment by Matheus456** [comment]
Show @GustavoAPS! O cliente deixou pendente a reposta sobre a logo, mas a princípio usaremos essa.
