### ISSUE TITLE
Definir nome da aplicação

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#28]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Gostaria que fosse definido um nome para o projeto.

**Descreva a solução que você gostaria**
Escolher um nome para o projeto, que se identifique com o escopo.

**Informações adicionais**
A definição do nome depende da issue #24

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by GustavoAPS** [comment]
Por meio de votação no grupo de desenvolvimento, o nome escolhido para a aplicação foi Amika, cujo significado em esperanto é amigável, tal nome é bastante adequado para a proposta do projeto, e é harmônico com a proposta de design visual da aplicação.

@Matheus456
@MateusO97
@cantuariavc
