### ISSUE TITLE
[DOC19] Atualizar README

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#57]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

O README atual não possui informações a respeito do projeto.

**Descreva a solução que você gostaria**

Adicionar informações gerais a respeito do produto, e informações rapidas sobre como levantar o ambiente e começar a desenvolver para o mesmo.

**Descreva uma alternativa considerada**

Seria interessante apresentar as seguintes informações:
- [x] Manutenibilidade
- [x] Cobertura de testes
- [x] Status da build
- [x] Licença utilizada
- [x] Introdução sobre a aplicação
- [ ] Prints de tela do produto ou protótipo
- [x] Tecnologias utilizadas
- [x] Link para documentação
- [x] Link para outros repositórios

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by cantuariavc** [comment]
@MateusO97, acredito que os pré-requisitos, o guia de como rodar a aplicação e como rodar os testes devam ficar nos readme dos repositórios com os códigos do backend e frontend.

**Comment by cantuariavc** [comment]
Comecei a escrever sobre as tecnologias utilizadas.

## Tecnologias Utilizadas

O projeto foi dividido em dois repositórios: o [2019.2-Amika-Backend](https://github.com/fga-eps-mds/2019.2-Amika-Backend) que é desenvolvido com o framework [Django](https://www.djangoproject.com) escrito em [Python](https://www.python.org) e o [2019.2-Amika-Frontend](https://github.com/fga-eps-mds/2019.2-Amika-Frontend) que é desenvolvido com o framework [Angular](https://angular.io) escrito em [TypeScript](https://www.typescriptlang.org). Os dois se comunicarão através de requisições HTTP.
