### ISSUE TITLE
[DOC16] Priorização de issues

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#58]
**Descreva a solução que você gostaria**

Refinamento das histórias do Backlog, melhorar o agrupamento entre histórias semelhantes e realizar a priorização de acordo com validação do cliente

**Descreva uma alternativa considerada**

- [x] Refinamento do backlog
- [x] Priorização do backlog

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
@MateusO97 essa não entraria como [DOC16] Priorização de issues? Que seria a issue que está no planejamento desta sprint? 
Fiquei na dúvida também se entraria como um DOC novo ou se só como uma issue, pois se trata de uma atualização do documento e não de um novo documento.

**Comment by MateusO97** [comment]
Acho q

> @MateusO97 essa não entraria como [DOC16] Priorização de issues? Que seria a issue que está no planejamento desta sprint?
> Fiquei na dúvida também se entraria como um DOC novo ou se só como uma issue, pois se trata de uma atualização do documento e não de um novo documento.

Acho que então seria só o caso de modificar o nome desta issue para [DOC16], como a Issue de priorização não estava criada tinha feito esta com esse intuito

**Comment by Matheus456** [comment]
Tranquilo, acho que podemos fazer isso mesmo
