### ISSUE TITLE
Adicionar descrição do repositório

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#7]
**Descreva a solução que você gostaria**

Adicionar breve descrição do repositório

**Descreva uma alternativa considerada**

Colocar informações básicas do time de desenvolvimento, breve descrição sobre o contexto da organização.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
Esse problema serár resolvido na issue #57
