### ISSUE TITLE
[DOC25] Plano de metodologia

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Wiki#75]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Documentar a metodologia que está sendo usada no projeto

**Descreva a solução que você gostaria**
Documentar metodologia ágil e seus papéis

**Descreva uma alternativa considerada**

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by MateusO97** [comment]
Resolvido em #91
