### ISSUE TITLE
Adicionar guia de contribuição para repositório

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Wiki#8]
**Descreva a solução que você gostaria**

Esse projeto necessita de um tutorial de como contribuir com o repositório

**Descreva uma alternativa considerada**

Criar um manual passo a passo explicando como contribuir com o projeto.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
@cantuariavc @MateusO97 É necessário adicionar alguns tópicos neste documento, o mesmo fala apenas sobre o processo para criação de um pull request. Sendo que também é necessário informar sobre o processo de criação de branches e de issues.

**Comment by Matheus456** [comment]
O problema foi resolvido no PR #54
